<a href="https://colab.research.google.com/github/hamza-24-ai/Pytorch_with_practical_deepLearning/blob/main/01_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"GPU Model is Using : {torch.cuda.get_device_name()}")
else:
  print("Gpu not available Using CPU")

GPU is available
GPU Model is Using : Tesla T4


# Tensor Creating

In [ ]:
# empty cell

torch.empty(size=(3,3))

tensor([[4.9335e-33, 4.5006e-41, 4.9335e-33],
        [4.5006e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
# zeros cell
torch.zeros(size=(4,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#Manual Seed
torch.manual_seed(100)
torch.rand(size=(3,4))
# The main concept if some one of your colleague run this code after few days
# later then the result will be same

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
# Using Eye in tensor
print("Identity Torach is been used")
torch.eye(3)

Identity Torach is been used


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Creating Tensor Shape

In [ ]:
x = torch.tensor(
   [ [1,2,3,4,5],
    [6,7,8,9,0] ]
)
x

tensor([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [ ]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.6941, 0.3464, 0.9751, 0.7911, 0.4274],
        [0.4460, 0.5522, 0.9559, 0.9405, 0.2215]], dtype=torch.float64)

# Arithmatic Operations on tensors

In [ ]:
x = torch.rand(size  =(2,2))
print(x)

tensor([[0.4868, 0.1095],
        [0.9687, 0.7630]])


In [ ]:
# Addition
a = x + 2
print(f"Addition Value \n {a}")
# multiplication
m = x * 100
print(f"Multiplication value \n {m}")
# division
d = m // 2
print(f"Division Value \n {d}")
# Power Value
p = x ** 2
print(f"Power Value \n {p}")



Addition Value 
 tensor([[2.4868, 2.1095],
        [2.9687, 2.7630]])
Multiplication value 
 tensor([[48.6773, 10.9457],
        [96.8748, 76.3001]])
Division Value 
 tensor([[24.,  5.],
        [48., 38.]])
Power Value 
 tensor([[0.2369, 0.0120],
        [0.9385, 0.5822]])


# CPU VS GPU

In [ ]:
import torch
import time

num = 10000

m1_c = torch.rand(size = (num,num))
m2_c = torch.rand(size = (num,num))

start_time = time.time()
mul_cpu = torch.matmul(m1_c,m2_c)
cpu_time = time.time() - start_time

print(f"Cpu Runing Time : {cpu_time:.4f}")

m1_g = m1_c.to("cuda")
m2_g = m2_c.to("cuda")

start = time.time()
result_gpu = torch.matmul(m1_g,m2_g)
torch.cuda.synchronize()
gpu_time = time.time() - start
print(f"GPU Runing Time : {gpu_time:.4f}")

Cpu Runing Time : 19.6105
GPU Runing Time : 0.6460
