<a href="https://colab.research.google.com/github/hamza-24-ai/Pytorch_with_practical_deepLearning/blob/main/02_Perceptron_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import torch.nn as nn
from sklearn.metrics import accuracy_score

# Data Import from Github

In [2]:
data_url = "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
df = pd.read_csv(data_url)

print("First five rows of the data ")
print(df.head())

First five rows of the data 
         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_

# Preprocessing the data

In [3]:
# Checking about the shape of data
print("Data shape")
print(df.shape)

# Checking if any value is null
print("\n Checking null values ")
print(df.isnull().sum())

Data shape
(569, 33)

 Checking null values 
id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst           

In [8]:
# Drop unnecessary columns
df = df.drop(columns = ["id", "Unnamed: 32"])
print("Updated data in dataflow table")
print(df.isnull().sum())

Updated data in dataflow table
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64


In [11]:
# Separating the input and output data
X = df.drop(columns = ["diagnosis"])
Y = df["diagnosis"]

# Now checking the data is it is separted or not
print("Input data ")
print(X.info())
print("\nOutput Data ")
print(Y.info())

Input data 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   radius_mean              569 non-null    float64
 1   texture_mean             569 non-null    float64
 2   perimeter_mean           569 non-null    float64
 3   area_mean                569 non-null    float64
 4   smoothness_mean          569 non-null    float64
 5   compactness_mean         569 non-null    float64
 6   concavity_mean           569 non-null    float64
 7   concave points_mean      569 non-null    float64
 8   symmetry_mean            569 non-null    float64
 9   fractal_dimension_mean   569 non-null    float64
 10  radius_se                569 non-null    float64
 11  texture_se               569 non-null    float64
 12  perimeter_se             569 non-null    float64
 13  area_se                  569 non-null    float64
 14  smoothness_se 

In [14]:
# Split the data

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Scaler the input data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Scaler the model Input data")
print(X_train)

# Lable encoding the output Data
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

print("\n Label Encoder model Output Data")
print(y_train)


Scaler the model Input data
[[-1.44075296 -0.43531947 -1.36208497 ...  0.9320124   2.09724217
   1.88645014]
 [ 1.97409619  1.73302577  2.09167167 ...  2.6989469   1.89116053
   2.49783848]
 [-1.39998202 -1.24962228 -1.34520926 ... -0.97023893  0.59760192
   0.0578942 ]
 ...
 [ 0.04880192 -0.55500086 -0.06512547 ... -1.23903365 -0.70863864
  -1.27145475]
 [-0.03896885  0.10207345 -0.03137406 ...  1.05001236  0.43432185
   1.21336207]
 [-0.54860557  0.31327591 -0.60350155 ... -0.61102866 -0.3345212
  -0.84628745]]

 Label Encoder model Output Data
[0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0
 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0
 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 0 1 0 1
 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0
 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 0 1

# numpy to Tensor

In [20]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

print("Input Data Tensor")
print(X_train_tensor)
print("\n Output Data Tensor")
print(y_train_tensor)

Input Data Tensor
tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

 Output Data Tensor
tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 1,

# Building Neural Network Model

In [33]:
class SimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

  # Now Wrtie a Neural Network

  def forward_propagation(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_calculation(self,y_pred,y):
    y = y.double()
    y = y.view(-1,1)
    criteria = nn.BCELoss()
    loss = criteria(y_pred,y)
    return loss


# Important Parameters

In [40]:
learning_rate = 0.1
epochs = 25

# Model Pipeline

In [35]:
model = SimpleNN(X_train_tensor)
model.weights

tensor([[0.2235],
        [0.0983],
        [0.0698],
        [0.8339],
        [0.4156],
        [0.8518],
        [0.8007],
        [0.0190],
        [0.3526],
        [0.3900],
        [0.5316],
        [0.8907],
        [0.4816],
        [0.7441],
        [0.0896],
        [0.2846],
        [0.5669],
        [0.2739],
        [0.4427],
        [0.3602],
        [0.6407],
        [0.4351],
        [0.8774],
        [0.4477],
        [0.8743],
        [0.3669],
        [0.7497],
        [0.0821],
        [0.0564],
        [0.9612]], dtype=torch.float64, requires_grad=True)

In [41]:
# Define models loop

for ep in range(epochs):
  # Forward propagation
  y_pred = model.forward_propagation(X_train_tensor)
  # Calculate Loss Function
  loss = model.loss_calculation(y_pred, y_train_tensor)

  # Backward propgation
  loss.backward()

  # Update Weight
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch No : {ep+1} , Loss : {loss}")




Epoch No : 1 , Loss : 0.08723286927714385
Epoch No : 2 , Loss : 0.0871260343962426
Epoch No : 3 , Loss : 0.08702035792421041
Epoch No : 4 , Loss : 0.08691580552530975
Epoch No : 5 , Loss : 0.0868123444246563
Epoch No : 6 , Loss : 0.08670994332244618
Epoch No : 7 , Loss : 0.08660857231364202
Epoch No : 8 , Loss : 0.08650820281271572
Epoch No : 9 , Loss : 0.0864088074830808
Epoch No : 10 , Loss : 0.08631036017087691
Epoch No : 11 , Loss : 0.08621283584279833
Epoch No : 12 , Loss : 0.08611621052768173
Epoch No : 13 , Loss : 0.08602046126159303
Epoch No : 14 , Loss : 0.08592556603617307
Epoch No : 15 , Loss : 0.08583150375002066
Epoch No : 16 , Loss : 0.08573825416290924
Epoch No : 17 , Loss : 0.08564579785264884
Epoch No : 18 , Loss : 0.0855541161744191
Epoch No : 19 , Loss : 0.08546319122241262
Epoch No : 20 , Loss : 0.08537300579363954
Epoch No : 21 , Loss : 0.08528354335375532
Epoch No : 22 , Loss : 0.08519478800478365
Epoch No : 23 , Loss : 0.08510672445461574
Epoch No : 24 , Loss : 0

# Model Evaluation

In [44]:
# Model Evaluate by forward propagation
with torch.no_grad():
  y_pre = model.forward_propagation(X_test_tensor)
  y_pre = (y_pre > 0.5).float()

acc = accuracy_score(y_pre, y_test_tensor)

print(f"Accuracy Score of our perceptron : {acc:.2f}")

Accuracy Score of our perceptron : 0.98
